### ISSUE TITLE
npm prerelease: add option to ignore pull requests opened by bot

### ISSUE THREAD

**Issue by targos** [zakodium/workflows#1]
Example: https://github.com/cheminfo/nmr-processing/pull/206

**Comment by targos** [comment]
Actually I'm going to make it opt-in (probably with a label). Otherwise it's too much noise

**Comment by targos** [comment]
Here's the proposal:
- Remove `pull_request` event
- Add `label` event. If there is a label added with the name `npm-prerelease`, the workflow will by triggered, do the prerelease and remove the label.

@lpatiny @stropitek WDYT?

**Comment by lpatiny** [comment]
How does it works to add this label ?

**Comment by targos** [comment]
Like any other label, with the sidebar of the pull request. It takes two clicks to create if it doesn't already exist

**Comment by lpatiny** [comment]
Ok and once this label is there for a specific PR it will be published continuously on each commit. But this means that if we create the PR and label it it will be published only on the next push. Is this right ?

Or we could from the console enter something like `gh pr create --label "npm-release" --fill` and this would trigger the publish.

This means that this workflow could then be added in all the projects without extra 'noise' 

I ping @jobo322 because it will concern him.

**Comment by targos** [comment]
> Ok and once this label is there for a specific PR it will be published continuously on each commit. But this means that if we create the PR and label it it will be published only on the next push. Is this right ?

That's not my proposal.

**Comment by stropitek** [comment]
SGTM

I think it's better if the prerelease is not created on every push. It's potentially better than a triggered action because we will have it in the PR timeline.

How will you choose a name for the prerelease? Will it be specific to every PR?

**Comment by targos** [comment]
> How will you choose a name for the prerelease? Will it be specific to every PR?

No, the name is based on the epoch value (`${pack.version)-pre.${epoch}`)
See https://www.npmjs.com/package/nmr-processing?activeTab=versions

**Comment by stropitek** [comment]
Would be useful to have a comment in the PR from the bot with name of the release

**Comment by targos** [comment]
Isn't what it already does enough (see link in the OP)

**Comment by targos** [comment]
@lpatiny to reword my proposal. This would be the new workflow:

- Create a PR
- When you are ready to test the changes, add the `npm-prerelease` label (can be done during the previous step)
- Workflow is triggered (by the label, not the PR) and creates a prerelease
- Workflow removes the label and adds a comment with the published npm version
- To create a new release after changes, add the label again.

**Comment by lpatiny** [comment]
Ok perfect thanks. It is what I understood (at the end).

**Comment by targos** [comment]
Seems to work! https://github.com/cheminfo/nmr-processing/pull/210

Note that I had to add the `read:org` permission to the bot token, otherwise it's not allowed to run `gh pr edit` (to remove the label).
