### ISSUE TITLE
Update release-please-action

### ISSUE THREAD

**Issue by targos** [zakodium/workflows#6]
Not an easy task: https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#upgrading-from-v3-to-v4

**Comment by targos** [comment]
The main issue with v4 is that a bunch of configuration that we could pass to the action has now to be set in a json file in the project being released. Whatever solution we come up with should not make this configuration file mandatory.

**Comment by targos** [comment]
I was trying to automatically create a config file before running release-please in https://github.com/zakodium/workflows/commits/release-please-v4/.
But [it didn't work](https://github.com/cheminfo/test-package/actions/runs/8170278640/job/22336100717) and I found out that the file has to live on the base branch, it is not read from the local file system (that's probably because release-please does everything using the GH API, it doesn't need a checkout): https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile

So there is no way to have a default/global config file.

The only solution I see is to remove our custom config. It currently has two fields:
- `bump-minor-pre-major`. I think this one is not a problem. We usually shouldn't keep 0.x version numbers for a long time. If it's necessary, we can add a config file directly in the project.
- `changelog-sections`. This is a bit more annoying because it was added so that `docs:` PRs trigger a release. But we can (and have historically) live without it.

@stropitek wdyt?

**Comment by stropitek** [comment]
I guess for `bump-minor-pre-major` we will notice the major bump in the release PR and add the config file if needed before releasing so that we don't get a major bump.

For `changelog-sections` it's indeed more annoying.

We should probably add the config file to our cheminfo-generator if we are still maintaining that.

**Comment by targos** [comment]
This will not help for the hundreds of repos that are already out there

**Comment by stropitek** [comment]
I can live with it
